### ISSUE TITLE
Is listed as "Nether Metals" in MultiMC.

### ISSUE THREAD

**Issue by xhaavardx** [nfinit-gaming/BetterAgriculture#1]
When I add Better Agriculture to the "Loader mods" list in MultiMC, the mod gets listed as Nether Metals instead of Better Agriculture.

**Comment by knoxhack** [comment]
do you have any log file?

**Comment by jriwanek** [comment]
No need:
https://github.com/nfinit-gaming/BetterAgriculture/blob/master/src/main/resources/pack.mcmeta

Just needs a fix there.

**Comment by xhaavardx** [comment]
I have put up a pull request in both branches to fix this, as well as the mcmod.info file :)

**Comment by knoxhack** [comment]
thank you again, the 1.9 version I just uploaded should have this fixed already, I'm about to upload a hotfix for 1.9.4

**Comment by knoxhack** [comment]
Hotfix for 1.9.4 has been uploaded
