### ISSUE TITLE
NullPointerException ItemStack

### ISSUE THREAD

**Issue by cap10zeus** [nfinit-gaming/BetterAgriculture#11]
FYI I got this crash updating pack.
http://pastebin.com/jz5R1bLJ

**Comment by knoxhack** [comment]
What version of BetterAgriculture are you using? And what version of Forge

**Comment by jriwanek** [comment]
Wake up knox, it's in the crash report:

 Forge 12.17.0.1976
    UCHE    betteragriculture{0.16} [Better Agriculture](BetterAgriculture_%28MC-1.10%29-0.16.jar)

**Comment by knoxhack** [comment]
Right -_-

**Comment by knoxhack** [comment]
Idk what this registry is doing there: (GameRegistry.addSmelting(ModBlocks.nethercoalOre, new ItemStack(Blocks.COAL_ORE, 2), 1.0f);)

**Comment by knoxhack** [comment]
It didn't crash on my end tho, we have been using on the public server. 
Can you give more description about when does the crash happen?

**Comment by jriwanek** [comment]
Looks like that particular line is a leftover from nether metals and can go.

**Comment by cap10zeus** [comment]
Found the mod it's conflicting with; RouterReborn.  https://bitbucket.org/zyberwax/main/issues/54/nullpointer

**Comment by tomevoll** [comment]
i cant see how it is conflicting, i add a recipe to smelting, for coal ore to coal, but that should not cause any issues with nethercoalOre

**Comment by tomevoll** [comment]
im also able to load BetterAgriculture and RR together and im not getting a crash

**Comment by cap10zeus** [comment]
Well darn, I didn't try it by themselves. Guess i gotta do it again with both installed and see who else could be the culprit.

**Comment by cap10zeus** [comment]
Ok, so here are my findings, when I have both BA and RouterReborn installed, the game crashes on startup with the following mods as well:
AbyssalCraft
BaseMetals
Forestry
IC2

**Comment by tomevoll** [comment]
this is only happening if RR is installed?

**Comment by tomevoll** [comment]
when i tested BA + RR i noticed JEI is complaining there is a null item in the smelting recipes, this only happends when BA is installed, Does not cause a crash though.

Not sure how a null item ends up in there, but dont look like forge has any checks that prevent you from adding a null item, i need to test some more to make sure im not the one that add this null item, but i do check for null before i auto add recipes, so not sure what is going on here.

**Comment by cap10zeus** [comment]
Yes happening when RR and BA are installed together along with the mods stated above.

**Comment by knoxhack** [comment]
This should fix this too https://github.com/MMDModding/BetterAgriculture/commit/f593564977cf21cec24fce93f6d0779d5d3f90fa
