### ISSUE TITLE
player auto jumps onto blocks

### ISSUE THREAD

**Issue by Faenum** [nfinit-gaming/BetterAgriculture#17]

**Comment by jriwanek** [comment]
If you're having that on 1.10.x, I think you'll find that it's a vanilla feature now.

**Comment by knoxhack** [comment]
-_- really

**Comment by Faenum** [comment]
Oh! Didnt know that, not played 1.10 other than to test the mod. I'm not sure I like it, don't wanna end up jumping on the kitchen counter just by walking up to it!

**Comment by jriwanek** [comment]
You can turn it off in the options menu.
