### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by Flashwar** [nfinit-gaming/BetterAgriculture#20]
When I´m starting my game, it crash with the this error log: 
http://pastebin.com/Q0FcsjF4

Minecraft:1.10.2
Forge: 1.10.2-12.18.1.2070

**Comment by knoxhack** [comment]
This should fix it. will be added to the next mod update https://github.com/MMDModding/BetterAgriculture/commit/f593564977cf21cec24fce93f6d0779d5d3f90fa

**Comment by Flashwar** [comment]
Thank you :)
