### ISSUE TITLE
No config documentation on entity

### ISSUE THREAD

**Issue by nearlyNonexistent** [nfinit-gaming/BetterAgriculture#21]
Every "Mob[x][y]" entry is meaningless if we can't tell which entity number is what. I'm wanting to make every special breed rare with vanilla the most frequent. (This helps prevent some bugs with cross-mod compatibility and makes them more unique to find and more worth collecting.) However, I cannot determine which one is vanilla without manually testing zeroing out all entities but one for each entity!

I will try reading your code and finding a solution to make the config more useful.

**Comment by knoxhack** [comment]
Update to latest version. The config file has been remade for easier use.
