### ISSUE TITLE
Can you inherit from the vanilla mobs instead of reimplementing them?

### ISSUE THREAD

**Issue by nearlyNonexistent** [nfinit-gaming/BetterAgriculture#23]
See title. If you could, say, inherit ClassChicken or whatever it's called in the Minecraft Forge code, you would be, presumably, compatible with any mod that changes vanilla mobs (e.g. Druidry makes it possible to milk cows with a bowl) naturally and have to write less redundant code. You could then focus on writing the differences FROM vanilla mobs, rather than reimplementing them.

**Comment by knoxhack** [comment]
Being implemented in the next update

**Comment by knoxhack** [comment]
Implemented :), let me know of any feedback
