### ISSUE TITLE
[1.10.2] Slate texture to big

### ISSUE THREAD

**Issue by Morpheus1101** [nfinit-gaming/BetterAgriculture#24]
When breaking the slate ore, the resulting slate texture is quite large, like the size of a tablet :D

**Comment by Faenum** [comment]
Slate used for roofing is quite large, lumps of slate are split into thin sheets before being cut to size. A slate tile is about the size of a 10 inch tablet, if not a bit bigger

**Comment by knoxhack** [comment]
Well fixed in version 1.0
