### ISSUE TITLE
texture derping BA:1.10-0.16

### ISSUE THREAD

**Issue by SDUBZ** [nfinit-gaming/BetterAgriculture#25]
i was walking around and i noticed this 
![2016-10-08_09 43 30](https://cloud.githubusercontent.com/assets/14084377/19207407/62bbc830-8d3c-11e6-8e72-1318dddc0453.png)

and also
![2016-10-08_09 43 46](https://cloud.githubusercontent.com/assets/14084377/19207412/6e226e86-8d3c-11e6-94df-9dbb195a7db5.png)

and: 
![2016-10-08_09 44 54](https://cloud.githubusercontent.com/assets/14084377/19207418/789faba8-8d3c-11e6-99ad-58042c73648f.png)

**Comment by knoxhack** [comment]
What other mods do you have installed.
Does it happen when only BA is the only mod installed?

**Comment by Morpheus1101** [comment]
I can confirm this has happend to me .. However the cause of this is the latest changes and update of JourneyMap being Journeymap 1.10.2-5.3.0b1-unlimited

https://bitbucket.org/TeamJM/journeymap/issues/122/1102-journeymap-1102-530b1-unlimited

**Comment by SDUBZ** [comment]
oh kool thanks rolled back one version of journeymap and now its fine wierd tho

**Comment by knoxhack** [comment]
this is a JourneyMap bug : https://twitter.com/JourneyMapMod/status/787111409788215298
