### ISSUE TITLE
BA Mobs and Reliquary

### ISSUE THREAD

**Issue by Discomanco** [nfinit-gaming/BetterAgriculture#26]
Not sure if this is an issue with Better Agriculture or Reliquary, but here it goes.
Mobs are not affected by Reliquary's items, such as Interdiction Torches (pushes mobs away) or Rending Gale (Push/Pull functions).
If this is an issue on Reliquarys part, let me know and I'll post it there too.

**Comment by knoxhack** [comment]
You should report it to Reliquary too

**Comment by Discomanco** [comment]
Case solved.
The Rending Gale and Interdiction Torch works on a whitelist that is only generated once, when the mod is added, and since we added BA later, they're not on the whitelist of said items.
