### ISSUE TITLE
farmland biome adjust in config

### ISSUE THREAD

**Issue by ShawnRHayes** [nfinit-gaming/BetterAgriculture#3]
seems like farmland is set way to high and overtakes other biomes in spawn freq . Please put in a configurable option

**Comment by knoxhack** [comment]
Sure will, probably on the next update. Thanks for your feedback

**Comment by knoxhack** [comment]
config for the Farmland Biome added http://minecraft.curseforge.com/projects/better-agriculture/files/2308103
