### ISSUE TITLE
 	 BetterAgriculture-[1.10.2]-1.0 - over 20 missing files

### ISSUE THREAD

**Issue by Iteries** [nfinit-gaming/BetterAgriculture#32]
Hello there!,
I don't know what happened between .16 to 1.0 of 10.2 but many many missing files on updating.  Example: spruce_trough, dark_oak_trough, helmet, etc.  Rather blew me away, so be back grading to fix it.  Thought I let you know there is a lot of issues in updating.

Iteries

**Comment by knoxhack** [comment]
most blocks are now using metadata, so 14 blocks only using 1 ID.before they all were different IDs, some blocks that are missing from old versions are still yet to be added
