### ISSUE TITLE
Journeymap icon problem

### ISSUE THREAD

**Issue by ghost** [nfinit-gaming/BetterAgriculture#36]
When using Better Agriculture with JourneyMap, the mob icons get... er... the animals all get flayed.
![screen shot 2016-12-01 at 3 09 31 pm](https://cloud.githubusercontent.com/assets/15851438/20816921/ab219344-b7d9-11e6-8d0c-77df5a354576.png)
![screen shot 2016-12-01 at 3 09 20 pm](https://cloud.githubusercontent.com/assets/15851438/20816922/ab229866-b7d9-11e6-9ee3-08ed390187ea.png)
I'll post on JM's BitBucket as well.
Thank you.

**Comment by Faenum** [comment]
Hmm, there must be an asset that journeymap uses thats somewhere in vanilla files, but not the mod. I shall have a look into it when i can and see about fixing it.

**Comment by knoxhack** [comment]
what version of both mods are you using?

**Comment by ghost** [comment]
I've been staring at the problem for a bit, but I just started a new instance with just those two and the most recent versions of everything (per the Curse client) and it was the same.
Minecraft: 1.10.2
Forge: 12.18.2.2171
JourneyMap: 1.10.2-5.3.1
BetterAgriculture: 1.0.1

**Comment by knoxhack** [comment]
https://bitbucket.org/TeamJM/journeymap/issues/138/icons-broken-with-better-agriculture
