### ISSUE TITLE
Crash with 1.11 Forge 2188

### ISSUE THREAD

**Issue by RayzoRayy** [nfinit-gaming/BetterAgriculture#37]
Get a crash on latest version of Forge as of today which is 2188. I think it has something to do with registering a biome, but could be wrong.  Anywho, here is the crash report.

http://pastebin.com/YKgsQX3Z

**Comment by knoxhack** [comment]
will update to latest forge this weekend hopefully

**Comment by shortybsd** [comment]
I am running the same version of Forge with the same exact error.

**Comment by shortybsd** [comment]
Any update on progress yet? Dying to put this in!

**Comment by knoxhack** [comment]
Update to latest version
