### ISSUE TITLE
Your Discord bot token is public.

### ISSUE THREAD

**Issue by lauriys** [nfinit-gaming/BetterAgriculture#4]

**Comment by knoxhack** [comment]
How so? Sorry I'm new to these discord bots.

**Comment by lauriys** [comment]
everyone can use your bot account because you uploaded the token to GitHub

**Comment by jriwanek** [comment]
@knoxhack And I did tell you not to post those files to github....

**Comment by knoxhack** [comment]
Derp me, bot taken renewed
