### ISSUE TITLE
[Suggestion] Review cost of tile blocks

### ISSUE THREAD

**Issue by xenoflot** [nfinit-gaming/BetterAgriculture#40]
Hi,

OK, so I started documenting this issue and then I kept running into quirks which makes me think that these are still a WIP :-) Since they are craftable but have "functional issues", perhaps you could disable tile blocks until they're done?

I've left my comments intact and I'll post this anyway, just in case you find the information useful. Feel free to use or ignore as you please.

---

I feel the cost of the tile blocks is way too high for what appears to be simple decorative block. Dyes are not super-common and IMO 6 lapis, 2 concrete and a slate for a single block is way too expensive.

Did you perhaps intend for these recipes to return more than a single item?
Also I feel that having different numbers of dye for the pattern is not a good design choice. 
I'd like to suggest the following:
* A single dye in the centre.
* Combinations of slate and concrete in different positions to create the different tile patterns.
* Return 8 or 16 blocks from the recipe.

Other things I've noticed:
* Tiny tiles are showing an unlocalized name.
* If I try to jump on them, I slide off!
* If press myself up against them, I take damage!

**Comment by Faenum** [comment]
Thanks for taking the time to give so much detai.
We are aware the tile blocks are buggy, and should have been fixed for the next update. The recipe is wrong, and should use clay with one dye in the centre, and should give out 8 blocks. This should also be fixed for the next update. The whole mod is a wip, so there will be some bugs, and there will eventualy be a lot more colour choices for the blocks.

**Comment by xenoflot** [comment]
No worries! I've included it in our new server pack which has a half dozen regulars at the moment. I'll be sure to pass on anything else we discover that seems noteworthy.

Cheers!

**Comment by Faenum** [comment]
Ideal, thank you. The more testing we can get, the better
Unfortunatly i cant code, as my brain just wont allow me to, so i have to rely on knox to code for me, while i do planning, concept, textures  and modeling. Knox also work full time so doesnt have a lot of time to code.
