### ISSUE TITLE
Slate / Copper Conflict?

### ISSUE THREAD

**Issue by Draco18s** [nfinit-gaming/BetterAgriculture#41]
One of my users has discovered a possible conflict beetween BA's slate ore and the hard copper ore supplied by my Reasonable Realism Harder Ores mod:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2451299-reasonable-realism-its-a-pack-its-a-mod-it-makes?comment=1104
Wanted to see if you had any insight.

**Comment by knoxhack** [comment]
Slate is no longer an ore, update to latest version
