### ISSUE TITLE
Crashy McCrashFace

### ISSUE THREAD

**Issue by bookerthegeek** [nfinit-gaming/BetterAgriculture#43]
## Versions
- Minecraft 1.10.2
- Forge 1.10.2-12.18.3.2254
- BetterAgriculture-[1.10.2]-1.0.1
- jei_1.10.2-3.14.7.416
## What Happens
Crash when trying to craft a Tank (I assume as they are listed as in game [HERE][4]) as that is what the recipe looks like it should be but alas there isn't a tank in your mod currently so I have no idea other then I should be getting four of them.
## What I expect to Happen
For the game not to crash when placing items in a crafting table.
Recipies not yet fully implemented to not return a null itemstack
##### Image taken in a vanilla instance so as not to crash
![Null Itemstack Recipe][1]
## Profit?
- [Crash Report][2]
- [Error in the Log][3]

[1]:http://i.imgur.com/0FFiDjB.png
[2]:https://gist.github.com/bookerthegeek/a0f5725b92552e6f791323c35422d9d8
[3]:https://gist.github.com/bookerthegeek/5928e5366e41cd017ff65bb968b0e4da
[4]:https://minecraft.curseforge.com/projects/better-agriculture?page=2

**Comment by bookerthegeek** [comment]
Any news on this?

**Comment by dshadowwolf** [comment]
Knox is on vacation right now and I don't know any other members of the team working on this mod. I've given him a poke, but gotten no response.

**Comment by Faenum** [comment]
Knox should be back, im actualy the creator of the mod, hes coding it for me while i do textures and concept. Hes been very busy so updates are slow. Tanks were removed while they are being worked on, im not sure why its crashing though, they are just deco blocks, that will work the same as a couldron. All i can say is avoid trying to craft them for now.

**Comment by bookerthegeek** [comment]
The issue is that while the item is being removed, the recipe for the item is still being registered.

**Comment by Faenum** [comment]
Im not sure why as it should have all been removed. They should be added back in the next version anyway

**Comment by knoxhack** [comment]
Update to latest version
