### ISSUE TITLE
Suggestion-Vanilla Mobs Config Option

### ISSUE THREAD

**Issue by WenXin20** [nfinit-gaming/BetterAgriculture#44]
I was wondering if vanilla mobs still spawn as well? If they don't, can there be a config option to enable as well? Just in case a mod needs the vanilla cow to do something.

**Comment by knoxhack** [comment]
Better Agriculture mobs now spawn on specific biomes. Vanilla mobs should spawn on any biomes we don't stop them from spawning but they are less common on biomes where our m9bs spawn
